/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as R404RouteImport } from './routes/_404'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as OrderConfirmationOrderIdRouteImport } from './routes/order-confirmation.$orderId'
import { Route as AdminUsersPermissionsRouteImport } from './routes/admin.users-permissions'
import { Route as AdminThemeRouteImport } from './routes/admin.theme'
import { Route as AdminShippingRouteImport } from './routes/admin.shipping'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPromoCodesRouteImport } from './routes/admin.promo-codes'
import { Route as AdminPlaceholderRouteImport } from './routes/admin.placeholder'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMobileAppRouteImport } from './routes/admin.mobile-app'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminLandingPagesRouteImport } from './routes/admin.landing-pages'
import { Route as AdminInvitesRouteImport } from './routes/admin.invites'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminPagesIndexRouteImport } from './routes/admin.pages.index'
import { Route as AdminManageShopIndexRouteImport } from './routes/admin.manage-shop.index'
import { Route as AdminCollectionsIndexRouteImport } from './routes/admin.collections.index'
import { Route as AdminWebsiteTestimonialRouteImport } from './routes/admin.website.testimonial'
import { Route as AdminWebsiteSubscriptionRouteImport } from './routes/admin.website.subscription'
import { Route as AdminWebsiteSliderRouteImport } from './routes/admin.website.slider'
import { Route as AdminWebsiteServiceRouteImport } from './routes/admin.website.service'
import { Route as AdminWebsiteSeoRouteImport } from './routes/admin.website.seo'
import { Route as AdminWebsiteSellerConditionsRouteImport } from './routes/admin.website.seller-conditions'
import { Route as AdminWebsiteMaintenanceRouteImport } from './routes/admin.website.maintenance'
import { Route as AdminWebsiteImageContentRouteImport } from './routes/admin.website.image-content'
import { Route as AdminWebsiteHomepageTitleRouteImport } from './routes/admin.website.homepage-title'
import { Route as AdminWebsiteDefaultAvatarRouteImport } from './routes/admin.website.default-avatar'
import { Route as AdminWebsiteAnnouncementRouteImport } from './routes/admin.website.announcement'
import { Route as AdminProductsTagsRouteImport } from './routes/admin.products.tags'
import { Route as AdminProductsPricesRouteImport } from './routes/admin.products.prices'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminProductsAttributesRouteImport } from './routes/admin.products.attributes'
import { Route as AdminProductsProductIdRouteImport } from './routes/admin.products.$productId'
import { Route as AdminPagesPageIdRouteImport } from './routes/admin.pages.$pageId'
import { Route as AdminOrdersShipmentsRouteImport } from './routes/admin.orders.shipments'
import { Route as AdminOrdersReturnsRouteImport } from './routes/admin.orders.returns'
import { Route as AdminOrdersInvoicesRouteImport } from './routes/admin.orders.invoices'
import { Route as AdminOrdersIncompleteRouteImport } from './routes/admin.orders.incomplete'
import { Route as AdminManageShopSocialRouteImport } from './routes/admin.manage-shop.social'
import { Route as AdminManageShopSmsRouteImport } from './routes/admin.manage-shop.sms'
import { Route as AdminManageShopSettingsRouteImport } from './routes/admin.manage-shop.settings'
import { Route as AdminManageShopSeoRouteImport } from './routes/admin.manage-shop.seo'
import { Route as AdminManageShopPolicyRouteImport } from './routes/admin.manage-shop.policy'
import { Route as AdminManageShopPaymentRouteImport } from './routes/admin.manage-shop.payment'
import { Route as AdminManageShopDomainRouteImport } from './routes/admin.manage-shop.domain'
import { Route as AdminManageShopDeliveryRouteImport } from './routes/admin.manage-shop.delivery'
import { Route as AdminManageShopChatRouteImport } from './routes/admin.manage-shop.chat'
import { Route as AdminCollectionsNewRouteImport } from './routes/admin.collections.new'
import { Route as AdminCollectionsCollectionIdRouteImport } from './routes/admin.collections.$collectionId'
import { Route as AdminPagesEditSlugRouteImport } from './routes/admin.pages.edit.$slug'
import { Route as AdminOrdersInvoiceOrderIdRouteImport } from './routes/admin.orders.invoice.$orderId'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/_404',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationOrderIdRoute =
  OrderConfirmationOrderIdRouteImport.update({
    id: '/order-confirmation/$orderId',
    path: '/order-confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersPermissionsRoute = AdminUsersPermissionsRouteImport.update({
  id: '/admin/users-permissions',
  path: '/admin/users-permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminThemeRoute = AdminThemeRouteImport.update({
  id: '/admin/theme',
  path: '/admin/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/admin/shipping',
  path: '/admin/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromoCodesRoute = AdminPromoCodesRouteImport.update({
  id: '/admin/promo-codes',
  path: '/admin/promo-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlaceholderRoute = AdminPlaceholderRouteImport.update({
  id: '/admin/placeholder',
  path: '/admin/placeholder',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMobileAppRoute = AdminMobileAppRouteImport.update({
  id: '/admin/mobile-app',
  path: '/admin/mobile-app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/admin/marketing',
  path: '/admin/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLandingPagesRoute = AdminLandingPagesRouteImport.update({
  id: '/admin/landing-pages',
  path: '/admin/landing-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvitesRoute = AdminInvitesRouteImport.update({
  id: '/admin/invites',
  path: '/admin/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesIndexRoute = AdminPagesIndexRouteImport.update({
  id: '/admin/pages/',
  path: '/admin/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManageShopIndexRoute = AdminManageShopIndexRouteImport.update({
  id: '/admin/manage-shop/',
  path: '/admin/manage-shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionsIndexRoute = AdminCollectionsIndexRouteImport.update({
  id: '/admin/collections/',
  path: '/admin/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteTestimonialRoute = AdminWebsiteTestimonialRouteImport.update({
  id: '/admin/website/testimonial',
  path: '/admin/website/testimonial',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteSubscriptionRoute =
  AdminWebsiteSubscriptionRouteImport.update({
    id: '/admin/website/subscription',
    path: '/admin/website/subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminWebsiteSliderRoute = AdminWebsiteSliderRouteImport.update({
  id: '/admin/website/slider',
  path: '/admin/website/slider',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteServiceRoute = AdminWebsiteServiceRouteImport.update({
  id: '/admin/website/service',
  path: '/admin/website/service',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteSeoRoute = AdminWebsiteSeoRouteImport.update({
  id: '/admin/website/seo',
  path: '/admin/website/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteSellerConditionsRoute =
  AdminWebsiteSellerConditionsRouteImport.update({
    id: '/admin/website/seller-conditions',
    path: '/admin/website/seller-conditions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminWebsiteMaintenanceRoute = AdminWebsiteMaintenanceRouteImport.update({
  id: '/admin/website/maintenance',
  path: '/admin/website/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteImageContentRoute =
  AdminWebsiteImageContentRouteImport.update({
    id: '/admin/website/image-content',
    path: '/admin/website/image-content',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminWebsiteHomepageTitleRoute =
  AdminWebsiteHomepageTitleRouteImport.update({
    id: '/admin/website/homepage-title',
    path: '/admin/website/homepage-title',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminWebsiteDefaultAvatarRoute =
  AdminWebsiteDefaultAvatarRouteImport.update({
    id: '/admin/website/default-avatar',
    path: '/admin/website/default-avatar',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminWebsiteAnnouncementRoute =
  AdminWebsiteAnnouncementRouteImport.update({
    id: '/admin/website/announcement',
    path: '/admin/website/announcement',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminProductsTagsRoute = AdminProductsTagsRouteImport.update({
  id: '/admin/products/tags',
  path: '/admin/products/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsPricesRoute = AdminProductsPricesRouteImport.update({
  id: '/admin/products/prices',
  path: '/admin/products/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/admin/products/new',
  path: '/admin/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsAttributesRoute = AdminProductsAttributesRouteImport.update({
  id: '/admin/products/attributes',
  path: '/admin/products/attributes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/admin/products/$productId',
  path: '/admin/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesPageIdRoute = AdminPagesPageIdRouteImport.update({
  id: '/admin/pages/$pageId',
  path: '/admin/pages/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersShipmentsRoute = AdminOrdersShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersReturnsRoute = AdminOrdersReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersInvoicesRoute = AdminOrdersInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersIncompleteRoute = AdminOrdersIncompleteRouteImport.update({
  id: '/incomplete',
  path: '/incomplete',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminManageShopSocialRoute = AdminManageShopSocialRouteImport.update({
  id: '/admin/manage-shop/social',
  path: '/admin/manage-shop/social',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManageShopSmsRoute = AdminManageShopSmsRouteImport.update({
  id: '/admin/manage-shop/sms',
  path: '/admin/manage-shop/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManageShopSettingsRoute = AdminManageShopSettingsRouteImport.update({
  id: '/admin/manage-shop/settings',
  path: '/admin/manage-shop/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManageShopSeoRoute = AdminManageShopSeoRouteImport.update({
  id: '/admin/manage-shop/seo',
  path: '/admin/manage-shop/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManageShopPolicyRoute = AdminManageShopPolicyRouteImport.update({
  id: '/admin/manage-shop/policy',
  path: '/admin/manage-shop/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManageShopPaymentRoute = AdminManageShopPaymentRouteImport.update({
  id: '/admin/manage-shop/payment',
  path: '/admin/manage-shop/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManageShopDomainRoute = AdminManageShopDomainRouteImport.update({
  id: '/admin/manage-shop/domain',
  path: '/admin/manage-shop/domain',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManageShopDeliveryRoute = AdminManageShopDeliveryRouteImport.update({
  id: '/admin/manage-shop/delivery',
  path: '/admin/manage-shop/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManageShopChatRoute = AdminManageShopChatRouteImport.update({
  id: '/admin/manage-shop/chat',
  path: '/admin/manage-shop/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionsNewRoute = AdminCollectionsNewRouteImport.update({
  id: '/admin/collections/new',
  path: '/admin/collections/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionsCollectionIdRoute =
  AdminCollectionsCollectionIdRouteImport.update({
    id: '/admin/collections/$collectionId',
    path: '/admin/collections/$collectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPagesEditSlugRoute = AdminPagesEditSlugRouteImport.update({
  id: '/admin/pages/edit/$slug',
  path: '/admin/pages/edit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersInvoiceOrderIdRoute =
  AdminOrdersInvoiceOrderIdRouteImport.update({
    id: '/invoice/$orderId',
    path: '/invoice/$orderId',
    getParentRoute: () => AdminOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/products': typeof ProductsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/mobile-app': typeof AdminMobileAppRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/placeholder': typeof AdminPlaceholderRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/users-permissions': typeof AdminUsersPermissionsRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/collections/$collectionId': typeof AdminCollectionsCollectionIdRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/manage-shop/chat': typeof AdminManageShopChatRoute
  '/admin/manage-shop/delivery': typeof AdminManageShopDeliveryRoute
  '/admin/manage-shop/domain': typeof AdminManageShopDomainRoute
  '/admin/manage-shop/payment': typeof AdminManageShopPaymentRoute
  '/admin/manage-shop/policy': typeof AdminManageShopPolicyRoute
  '/admin/manage-shop/seo': typeof AdminManageShopSeoRoute
  '/admin/manage-shop/settings': typeof AdminManageShopSettingsRoute
  '/admin/manage-shop/sms': typeof AdminManageShopSmsRoute
  '/admin/manage-shop/social': typeof AdminManageShopSocialRoute
  '/admin/orders/incomplete': typeof AdminOrdersIncompleteRoute
  '/admin/orders/invoices': typeof AdminOrdersInvoicesRoute
  '/admin/orders/returns': typeof AdminOrdersReturnsRoute
  '/admin/orders/shipments': typeof AdminOrdersShipmentsRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/attributes': typeof AdminProductsAttributesRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/prices': typeof AdminProductsPricesRoute
  '/admin/products/tags': typeof AdminProductsTagsRoute
  '/admin/website/announcement': typeof AdminWebsiteAnnouncementRoute
  '/admin/website/default-avatar': typeof AdminWebsiteDefaultAvatarRoute
  '/admin/website/homepage-title': typeof AdminWebsiteHomepageTitleRoute
  '/admin/website/image-content': typeof AdminWebsiteImageContentRoute
  '/admin/website/maintenance': typeof AdminWebsiteMaintenanceRoute
  '/admin/website/seller-conditions': typeof AdminWebsiteSellerConditionsRoute
  '/admin/website/seo': typeof AdminWebsiteSeoRoute
  '/admin/website/service': typeof AdminWebsiteServiceRoute
  '/admin/website/slider': typeof AdminWebsiteSliderRoute
  '/admin/website/subscription': typeof AdminWebsiteSubscriptionRoute
  '/admin/website/testimonial': typeof AdminWebsiteTestimonialRoute
  '/admin/collections': typeof AdminCollectionsIndexRoute
  '/admin/manage-shop': typeof AdminManageShopIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/orders/invoice/$orderId': typeof AdminOrdersInvoiceOrderIdRoute
  '/admin/pages/edit/$slug': typeof AdminPagesEditSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/products': typeof ProductsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/mobile-app': typeof AdminMobileAppRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/placeholder': typeof AdminPlaceholderRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/users-permissions': typeof AdminUsersPermissionsRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/collections/$collectionId': typeof AdminCollectionsCollectionIdRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/manage-shop/chat': typeof AdminManageShopChatRoute
  '/admin/manage-shop/delivery': typeof AdminManageShopDeliveryRoute
  '/admin/manage-shop/domain': typeof AdminManageShopDomainRoute
  '/admin/manage-shop/payment': typeof AdminManageShopPaymentRoute
  '/admin/manage-shop/policy': typeof AdminManageShopPolicyRoute
  '/admin/manage-shop/seo': typeof AdminManageShopSeoRoute
  '/admin/manage-shop/settings': typeof AdminManageShopSettingsRoute
  '/admin/manage-shop/sms': typeof AdminManageShopSmsRoute
  '/admin/manage-shop/social': typeof AdminManageShopSocialRoute
  '/admin/orders/incomplete': typeof AdminOrdersIncompleteRoute
  '/admin/orders/invoices': typeof AdminOrdersInvoicesRoute
  '/admin/orders/returns': typeof AdminOrdersReturnsRoute
  '/admin/orders/shipments': typeof AdminOrdersShipmentsRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/attributes': typeof AdminProductsAttributesRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/prices': typeof AdminProductsPricesRoute
  '/admin/products/tags': typeof AdminProductsTagsRoute
  '/admin/website/announcement': typeof AdminWebsiteAnnouncementRoute
  '/admin/website/default-avatar': typeof AdminWebsiteDefaultAvatarRoute
  '/admin/website/homepage-title': typeof AdminWebsiteHomepageTitleRoute
  '/admin/website/image-content': typeof AdminWebsiteImageContentRoute
  '/admin/website/maintenance': typeof AdminWebsiteMaintenanceRoute
  '/admin/website/seller-conditions': typeof AdminWebsiteSellerConditionsRoute
  '/admin/website/seo': typeof AdminWebsiteSeoRoute
  '/admin/website/service': typeof AdminWebsiteServiceRoute
  '/admin/website/slider': typeof AdminWebsiteSliderRoute
  '/admin/website/subscription': typeof AdminWebsiteSubscriptionRoute
  '/admin/website/testimonial': typeof AdminWebsiteTestimonialRoute
  '/admin/collections': typeof AdminCollectionsIndexRoute
  '/admin/manage-shop': typeof AdminManageShopIndexRoute
  '/admin/pages': typeof AdminPagesIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/orders/invoice/$orderId': typeof AdminOrdersInvoiceOrderIdRoute
  '/admin/pages/edit/$slug': typeof AdminPagesEditSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_404': typeof R404Route
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/products': typeof ProductsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/landing-pages': typeof AdminLandingPagesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/mobile-app': typeof AdminMobileAppRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/placeholder': typeof AdminPlaceholderRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/users-permissions': typeof AdminUsersPermissionsRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/collections/$collectionId': typeof AdminCollectionsCollectionIdRoute
  '/admin/collections/new': typeof AdminCollectionsNewRoute
  '/admin/manage-shop/chat': typeof AdminManageShopChatRoute
  '/admin/manage-shop/delivery': typeof AdminManageShopDeliveryRoute
  '/admin/manage-shop/domain': typeof AdminManageShopDomainRoute
  '/admin/manage-shop/payment': typeof AdminManageShopPaymentRoute
  '/admin/manage-shop/policy': typeof AdminManageShopPolicyRoute
  '/admin/manage-shop/seo': typeof AdminManageShopSeoRoute
  '/admin/manage-shop/settings': typeof AdminManageShopSettingsRoute
  '/admin/manage-shop/sms': typeof AdminManageShopSmsRoute
  '/admin/manage-shop/social': typeof AdminManageShopSocialRoute
  '/admin/orders/incomplete': typeof AdminOrdersIncompleteRoute
  '/admin/orders/invoices': typeof AdminOrdersInvoicesRoute
  '/admin/orders/returns': typeof AdminOrdersReturnsRoute
  '/admin/orders/shipments': typeof AdminOrdersShipmentsRoute
  '/admin/pages/$pageId': typeof AdminPagesPageIdRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/attributes': typeof AdminProductsAttributesRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/products/prices': typeof AdminProductsPricesRoute
  '/admin/products/tags': typeof AdminProductsTagsRoute
  '/admin/website/announcement': typeof AdminWebsiteAnnouncementRoute
  '/admin/website/default-avatar': typeof AdminWebsiteDefaultAvatarRoute
  '/admin/website/homepage-title': typeof AdminWebsiteHomepageTitleRoute
  '/admin/website/image-content': typeof AdminWebsiteImageContentRoute
  '/admin/website/maintenance': typeof AdminWebsiteMaintenanceRoute
  '/admin/website/seller-conditions': typeof AdminWebsiteSellerConditionsRoute
  '/admin/website/seo': typeof AdminWebsiteSeoRoute
  '/admin/website/service': typeof AdminWebsiteServiceRoute
  '/admin/website/slider': typeof AdminWebsiteSliderRoute
  '/admin/website/subscription': typeof AdminWebsiteSubscriptionRoute
  '/admin/website/testimonial': typeof AdminWebsiteTestimonialRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/manage-shop/': typeof AdminManageShopIndexRoute
  '/admin/pages/': typeof AdminPagesIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/orders/invoice/$orderId': typeof AdminOrdersInvoiceOrderIdRoute
  '/admin/pages/edit/$slug': typeof AdminPagesEditSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/invites'
    | '/admin/landing-pages'
    | '/admin/marketing'
    | '/admin/mobile-app'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/placeholder'
    | '/admin/promo-codes'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/theme'
    | '/admin/users-permissions'
    | '/order-confirmation/$orderId'
    | '/product/$id'
    | '/admin'
    | '/admin/collections/$collectionId'
    | '/admin/collections/new'
    | '/admin/manage-shop/chat'
    | '/admin/manage-shop/delivery'
    | '/admin/manage-shop/domain'
    | '/admin/manage-shop/payment'
    | '/admin/manage-shop/policy'
    | '/admin/manage-shop/seo'
    | '/admin/manage-shop/settings'
    | '/admin/manage-shop/sms'
    | '/admin/manage-shop/social'
    | '/admin/orders/incomplete'
    | '/admin/orders/invoices'
    | '/admin/orders/returns'
    | '/admin/orders/shipments'
    | '/admin/pages/$pageId'
    | '/admin/products/$productId'
    | '/admin/products/attributes'
    | '/admin/products/new'
    | '/admin/products/prices'
    | '/admin/products/tags'
    | '/admin/website/announcement'
    | '/admin/website/default-avatar'
    | '/admin/website/homepage-title'
    | '/admin/website/image-content'
    | '/admin/website/maintenance'
    | '/admin/website/seller-conditions'
    | '/admin/website/seo'
    | '/admin/website/service'
    | '/admin/website/slider'
    | '/admin/website/subscription'
    | '/admin/website/testimonial'
    | '/admin/collections'
    | '/admin/manage-shop'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/orders/invoice/$orderId'
    | '/admin/pages/edit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/invites'
    | '/admin/landing-pages'
    | '/admin/marketing'
    | '/admin/mobile-app'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/placeholder'
    | '/admin/promo-codes'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/theme'
    | '/admin/users-permissions'
    | '/order-confirmation/$orderId'
    | '/product/$id'
    | '/admin'
    | '/admin/collections/$collectionId'
    | '/admin/collections/new'
    | '/admin/manage-shop/chat'
    | '/admin/manage-shop/delivery'
    | '/admin/manage-shop/domain'
    | '/admin/manage-shop/payment'
    | '/admin/manage-shop/policy'
    | '/admin/manage-shop/seo'
    | '/admin/manage-shop/settings'
    | '/admin/manage-shop/sms'
    | '/admin/manage-shop/social'
    | '/admin/orders/incomplete'
    | '/admin/orders/invoices'
    | '/admin/orders/returns'
    | '/admin/orders/shipments'
    | '/admin/pages/$pageId'
    | '/admin/products/$productId'
    | '/admin/products/attributes'
    | '/admin/products/new'
    | '/admin/products/prices'
    | '/admin/products/tags'
    | '/admin/website/announcement'
    | '/admin/website/default-avatar'
    | '/admin/website/homepage-title'
    | '/admin/website/image-content'
    | '/admin/website/maintenance'
    | '/admin/website/seller-conditions'
    | '/admin/website/seo'
    | '/admin/website/service'
    | '/admin/website/slider'
    | '/admin/website/subscription'
    | '/admin/website/testimonial'
    | '/admin/collections'
    | '/admin/manage-shop'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/orders/invoice/$orderId'
    | '/admin/pages/edit/$slug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_404'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/products'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/inventory'
    | '/admin/invites'
    | '/admin/landing-pages'
    | '/admin/marketing'
    | '/admin/mobile-app'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/placeholder'
    | '/admin/promo-codes'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/theme'
    | '/admin/users-permissions'
    | '/order-confirmation/$orderId'
    | '/product/$id'
    | '/admin/'
    | '/admin/collections/$collectionId'
    | '/admin/collections/new'
    | '/admin/manage-shop/chat'
    | '/admin/manage-shop/delivery'
    | '/admin/manage-shop/domain'
    | '/admin/manage-shop/payment'
    | '/admin/manage-shop/policy'
    | '/admin/manage-shop/seo'
    | '/admin/manage-shop/settings'
    | '/admin/manage-shop/sms'
    | '/admin/manage-shop/social'
    | '/admin/orders/incomplete'
    | '/admin/orders/invoices'
    | '/admin/orders/returns'
    | '/admin/orders/shipments'
    | '/admin/pages/$pageId'
    | '/admin/products/$productId'
    | '/admin/products/attributes'
    | '/admin/products/new'
    | '/admin/products/prices'
    | '/admin/products/tags'
    | '/admin/website/announcement'
    | '/admin/website/default-avatar'
    | '/admin/website/homepage-title'
    | '/admin/website/image-content'
    | '/admin/website/maintenance'
    | '/admin/website/seller-conditions'
    | '/admin/website/seo'
    | '/admin/website/service'
    | '/admin/website/slider'
    | '/admin/website/subscription'
    | '/admin/website/testimonial'
    | '/admin/collections/'
    | '/admin/manage-shop/'
    | '/admin/pages/'
    | '/admin/products/'
    | '/admin/orders/invoice/$orderId'
    | '/admin/pages/edit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R404Route: typeof R404Route
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ProductsRoute: typeof ProductsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminInvitesRoute: typeof AdminInvitesRoute
  AdminLandingPagesRoute: typeof AdminLandingPagesRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminMobileAppRoute: typeof AdminMobileAppRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlaceholderRoute: typeof AdminPlaceholderRoute
  AdminPromoCodesRoute: typeof AdminPromoCodesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminThemeRoute: typeof AdminThemeRoute
  AdminUsersPermissionsRoute: typeof AdminUsersPermissionsRoute
  OrderConfirmationOrderIdRoute: typeof OrderConfirmationOrderIdRoute
  ProductIdRoute: typeof ProductIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCollectionsCollectionIdRoute: typeof AdminCollectionsCollectionIdRoute
  AdminCollectionsNewRoute: typeof AdminCollectionsNewRoute
  AdminManageShopChatRoute: typeof AdminManageShopChatRoute
  AdminManageShopDeliveryRoute: typeof AdminManageShopDeliveryRoute
  AdminManageShopDomainRoute: typeof AdminManageShopDomainRoute
  AdminManageShopPaymentRoute: typeof AdminManageShopPaymentRoute
  AdminManageShopPolicyRoute: typeof AdminManageShopPolicyRoute
  AdminManageShopSeoRoute: typeof AdminManageShopSeoRoute
  AdminManageShopSettingsRoute: typeof AdminManageShopSettingsRoute
  AdminManageShopSmsRoute: typeof AdminManageShopSmsRoute
  AdminManageShopSocialRoute: typeof AdminManageShopSocialRoute
  AdminPagesPageIdRoute: typeof AdminPagesPageIdRoute
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
  AdminProductsAttributesRoute: typeof AdminProductsAttributesRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsPricesRoute: typeof AdminProductsPricesRoute
  AdminProductsTagsRoute: typeof AdminProductsTagsRoute
  AdminWebsiteAnnouncementRoute: typeof AdminWebsiteAnnouncementRoute
  AdminWebsiteDefaultAvatarRoute: typeof AdminWebsiteDefaultAvatarRoute
  AdminWebsiteHomepageTitleRoute: typeof AdminWebsiteHomepageTitleRoute
  AdminWebsiteImageContentRoute: typeof AdminWebsiteImageContentRoute
  AdminWebsiteMaintenanceRoute: typeof AdminWebsiteMaintenanceRoute
  AdminWebsiteSellerConditionsRoute: typeof AdminWebsiteSellerConditionsRoute
  AdminWebsiteSeoRoute: typeof AdminWebsiteSeoRoute
  AdminWebsiteServiceRoute: typeof AdminWebsiteServiceRoute
  AdminWebsiteSliderRoute: typeof AdminWebsiteSliderRoute
  AdminWebsiteSubscriptionRoute: typeof AdminWebsiteSubscriptionRoute
  AdminWebsiteTestimonialRoute: typeof AdminWebsiteTestimonialRoute
  AdminCollectionsIndexRoute: typeof AdminCollectionsIndexRoute
  AdminManageShopIndexRoute: typeof AdminManageShopIndexRoute
  AdminPagesIndexRoute: typeof AdminPagesIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminPagesEditSlugRoute: typeof AdminPagesEditSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_404': {
      id: '/_404'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation/$orderId': {
      id: '/order-confirmation/$orderId'
      path: '/order-confirmation/$orderId'
      fullPath: '/order-confirmation/$orderId'
      preLoaderRoute: typeof OrderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users-permissions': {
      id: '/admin/users-permissions'
      path: '/admin/users-permissions'
      fullPath: '/admin/users-permissions'
      preLoaderRoute: typeof AdminUsersPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/theme': {
      id: '/admin/theme'
      path: '/admin/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/admin/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promo-codes': {
      id: '/admin/promo-codes'
      path: '/admin/promo-codes'
      fullPath: '/admin/promo-codes'
      preLoaderRoute: typeof AdminPromoCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/placeholder': {
      id: '/admin/placeholder'
      path: '/admin/placeholder'
      fullPath: '/admin/placeholder'
      preLoaderRoute: typeof AdminPlaceholderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mobile-app': {
      id: '/admin/mobile-app'
      path: '/admin/mobile-app'
      fullPath: '/admin/mobile-app'
      preLoaderRoute: typeof AdminMobileAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/admin/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/landing-pages': {
      id: '/admin/landing-pages'
      path: '/admin/landing-pages'
      fullPath: '/admin/landing-pages'
      preLoaderRoute: typeof AdminLandingPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invites': {
      id: '/admin/invites'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AdminInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages/': {
      id: '/admin/pages/'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manage-shop/': {
      id: '/admin/manage-shop/'
      path: '/admin/manage-shop'
      fullPath: '/admin/manage-shop'
      preLoaderRoute: typeof AdminManageShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collections/': {
      id: '/admin/collections/'
      path: '/admin/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website/testimonial': {
      id: '/admin/website/testimonial'
      path: '/admin/website/testimonial'
      fullPath: '/admin/website/testimonial'
      preLoaderRoute: typeof AdminWebsiteTestimonialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website/subscription': {
      id: '/admin/website/subscription'
      path: '/admin/website/subscription'
      fullPath: '/admin/website/subscription'
      preLoaderRoute: typeof AdminWebsiteSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website/slider': {
      id: '/admin/website/slider'
      path: '/admin/website/slider'
      fullPath: '/admin/website/slider'
      preLoaderRoute: typeof AdminWebsiteSliderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website/service': {
      id: '/admin/website/service'
      path: '/admin/website/service'
      fullPath: '/admin/website/service'
      preLoaderRoute: typeof AdminWebsiteServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website/seo': {
      id: '/admin/website/seo'
      path: '/admin/website/seo'
      fullPath: '/admin/website/seo'
      preLoaderRoute: typeof AdminWebsiteSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website/seller-conditions': {
      id: '/admin/website/seller-conditions'
      path: '/admin/website/seller-conditions'
      fullPath: '/admin/website/seller-conditions'
      preLoaderRoute: typeof AdminWebsiteSellerConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website/maintenance': {
      id: '/admin/website/maintenance'
      path: '/admin/website/maintenance'
      fullPath: '/admin/website/maintenance'
      preLoaderRoute: typeof AdminWebsiteMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website/image-content': {
      id: '/admin/website/image-content'
      path: '/admin/website/image-content'
      fullPath: '/admin/website/image-content'
      preLoaderRoute: typeof AdminWebsiteImageContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website/homepage-title': {
      id: '/admin/website/homepage-title'
      path: '/admin/website/homepage-title'
      fullPath: '/admin/website/homepage-title'
      preLoaderRoute: typeof AdminWebsiteHomepageTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website/default-avatar': {
      id: '/admin/website/default-avatar'
      path: '/admin/website/default-avatar'
      fullPath: '/admin/website/default-avatar'
      preLoaderRoute: typeof AdminWebsiteDefaultAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website/announcement': {
      id: '/admin/website/announcement'
      path: '/admin/website/announcement'
      fullPath: '/admin/website/announcement'
      preLoaderRoute: typeof AdminWebsiteAnnouncementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/tags': {
      id: '/admin/products/tags'
      path: '/admin/products/tags'
      fullPath: '/admin/products/tags'
      preLoaderRoute: typeof AdminProductsTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/prices': {
      id: '/admin/products/prices'
      path: '/admin/products/prices'
      fullPath: '/admin/products/prices'
      preLoaderRoute: typeof AdminProductsPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/admin/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/attributes': {
      id: '/admin/products/attributes'
      path: '/admin/products/attributes'
      fullPath: '/admin/products/attributes'
      preLoaderRoute: typeof AdminProductsAttributesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$productId': {
      id: '/admin/products/$productId'
      path: '/admin/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages/$pageId': {
      id: '/admin/pages/$pageId'
      path: '/admin/pages/$pageId'
      fullPath: '/admin/pages/$pageId'
      preLoaderRoute: typeof AdminPagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/shipments': {
      id: '/admin/orders/shipments'
      path: '/shipments'
      fullPath: '/admin/orders/shipments'
      preLoaderRoute: typeof AdminOrdersShipmentsRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/orders/returns': {
      id: '/admin/orders/returns'
      path: '/returns'
      fullPath: '/admin/orders/returns'
      preLoaderRoute: typeof AdminOrdersReturnsRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/orders/invoices': {
      id: '/admin/orders/invoices'
      path: '/invoices'
      fullPath: '/admin/orders/invoices'
      preLoaderRoute: typeof AdminOrdersInvoicesRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/orders/incomplete': {
      id: '/admin/orders/incomplete'
      path: '/incomplete'
      fullPath: '/admin/orders/incomplete'
      preLoaderRoute: typeof AdminOrdersIncompleteRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/manage-shop/social': {
      id: '/admin/manage-shop/social'
      path: '/admin/manage-shop/social'
      fullPath: '/admin/manage-shop/social'
      preLoaderRoute: typeof AdminManageShopSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manage-shop/sms': {
      id: '/admin/manage-shop/sms'
      path: '/admin/manage-shop/sms'
      fullPath: '/admin/manage-shop/sms'
      preLoaderRoute: typeof AdminManageShopSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manage-shop/settings': {
      id: '/admin/manage-shop/settings'
      path: '/admin/manage-shop/settings'
      fullPath: '/admin/manage-shop/settings'
      preLoaderRoute: typeof AdminManageShopSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manage-shop/seo': {
      id: '/admin/manage-shop/seo'
      path: '/admin/manage-shop/seo'
      fullPath: '/admin/manage-shop/seo'
      preLoaderRoute: typeof AdminManageShopSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manage-shop/policy': {
      id: '/admin/manage-shop/policy'
      path: '/admin/manage-shop/policy'
      fullPath: '/admin/manage-shop/policy'
      preLoaderRoute: typeof AdminManageShopPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manage-shop/payment': {
      id: '/admin/manage-shop/payment'
      path: '/admin/manage-shop/payment'
      fullPath: '/admin/manage-shop/payment'
      preLoaderRoute: typeof AdminManageShopPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manage-shop/domain': {
      id: '/admin/manage-shop/domain'
      path: '/admin/manage-shop/domain'
      fullPath: '/admin/manage-shop/domain'
      preLoaderRoute: typeof AdminManageShopDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manage-shop/delivery': {
      id: '/admin/manage-shop/delivery'
      path: '/admin/manage-shop/delivery'
      fullPath: '/admin/manage-shop/delivery'
      preLoaderRoute: typeof AdminManageShopDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manage-shop/chat': {
      id: '/admin/manage-shop/chat'
      path: '/admin/manage-shop/chat'
      fullPath: '/admin/manage-shop/chat'
      preLoaderRoute: typeof AdminManageShopChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collections/new': {
      id: '/admin/collections/new'
      path: '/admin/collections/new'
      fullPath: '/admin/collections/new'
      preLoaderRoute: typeof AdminCollectionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collections/$collectionId': {
      id: '/admin/collections/$collectionId'
      path: '/admin/collections/$collectionId'
      fullPath: '/admin/collections/$collectionId'
      preLoaderRoute: typeof AdminCollectionsCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages/edit/$slug': {
      id: '/admin/pages/edit/$slug'
      path: '/admin/pages/edit/$slug'
      fullPath: '/admin/pages/edit/$slug'
      preLoaderRoute: typeof AdminPagesEditSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/invoice/$orderId': {
      id: '/admin/orders/invoice/$orderId'
      path: '/invoice/$orderId'
      fullPath: '/admin/orders/invoice/$orderId'
      preLoaderRoute: typeof AdminOrdersInvoiceOrderIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
  }
}

interface AdminOrdersRouteChildren {
  AdminOrdersIncompleteRoute: typeof AdminOrdersIncompleteRoute
  AdminOrdersInvoicesRoute: typeof AdminOrdersInvoicesRoute
  AdminOrdersReturnsRoute: typeof AdminOrdersReturnsRoute
  AdminOrdersShipmentsRoute: typeof AdminOrdersShipmentsRoute
  AdminOrdersInvoiceOrderIdRoute: typeof AdminOrdersInvoiceOrderIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIncompleteRoute: AdminOrdersIncompleteRoute,
  AdminOrdersInvoicesRoute: AdminOrdersInvoicesRoute,
  AdminOrdersReturnsRoute: AdminOrdersReturnsRoute,
  AdminOrdersShipmentsRoute: AdminOrdersShipmentsRoute,
  AdminOrdersInvoiceOrderIdRoute: AdminOrdersInvoiceOrderIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R404Route: R404Route,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ProductsRoute: ProductsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminInvitesRoute: AdminInvitesRoute,
  AdminLandingPagesRoute: AdminLandingPagesRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminMobileAppRoute: AdminMobileAppRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlaceholderRoute: AdminPlaceholderRoute,
  AdminPromoCodesRoute: AdminPromoCodesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminThemeRoute: AdminThemeRoute,
  AdminUsersPermissionsRoute: AdminUsersPermissionsRoute,
  OrderConfirmationOrderIdRoute: OrderConfirmationOrderIdRoute,
  ProductIdRoute: ProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCollectionsCollectionIdRoute: AdminCollectionsCollectionIdRoute,
  AdminCollectionsNewRoute: AdminCollectionsNewRoute,
  AdminManageShopChatRoute: AdminManageShopChatRoute,
  AdminManageShopDeliveryRoute: AdminManageShopDeliveryRoute,
  AdminManageShopDomainRoute: AdminManageShopDomainRoute,
  AdminManageShopPaymentRoute: AdminManageShopPaymentRoute,
  AdminManageShopPolicyRoute: AdminManageShopPolicyRoute,
  AdminManageShopSeoRoute: AdminManageShopSeoRoute,
  AdminManageShopSettingsRoute: AdminManageShopSettingsRoute,
  AdminManageShopSmsRoute: AdminManageShopSmsRoute,
  AdminManageShopSocialRoute: AdminManageShopSocialRoute,
  AdminPagesPageIdRoute: AdminPagesPageIdRoute,
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
  AdminProductsAttributesRoute: AdminProductsAttributesRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsPricesRoute: AdminProductsPricesRoute,
  AdminProductsTagsRoute: AdminProductsTagsRoute,
  AdminWebsiteAnnouncementRoute: AdminWebsiteAnnouncementRoute,
  AdminWebsiteDefaultAvatarRoute: AdminWebsiteDefaultAvatarRoute,
  AdminWebsiteHomepageTitleRoute: AdminWebsiteHomepageTitleRoute,
  AdminWebsiteImageContentRoute: AdminWebsiteImageContentRoute,
  AdminWebsiteMaintenanceRoute: AdminWebsiteMaintenanceRoute,
  AdminWebsiteSellerConditionsRoute: AdminWebsiteSellerConditionsRoute,
  AdminWebsiteSeoRoute: AdminWebsiteSeoRoute,
  AdminWebsiteServiceRoute: AdminWebsiteServiceRoute,
  AdminWebsiteSliderRoute: AdminWebsiteSliderRoute,
  AdminWebsiteSubscriptionRoute: AdminWebsiteSubscriptionRoute,
  AdminWebsiteTestimonialRoute: AdminWebsiteTestimonialRoute,
  AdminCollectionsIndexRoute: AdminCollectionsIndexRoute,
  AdminManageShopIndexRoute: AdminManageShopIndexRoute,
  AdminPagesIndexRoute: AdminPagesIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminPagesEditSlugRoute: AdminPagesEditSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
